### ISSUE TITLE
Use beforeDraw to prevent overlapping

### ISSUE THREAD

**Issue by Rowno** [chartjs/Chart.Annotation.js#1]
Consider using beforeDraw (or make it an option) so that the annotation doesn't overlap other chart elements. Currently the annotation gets drawn over tooltips. I can send through a pull request if you want.

![image](https://cloud.githubusercontent.com/assets/605501/15592337/d3371c76-2357-11e6-9646-1ff7047113f9.png)

![image](https://cloud.githubusercontent.com/assets/605501/15592411/620745f2-2358-11e6-985f-a56917ce1222.png)

**Comment by etimberg** [comment]
@Rowno sorry that I didn't respond to this sooner. Can you submit a PR that adds an option to toggle there the draw happens?

**Comment by Adondriel** [comment]
I just did this in my branch that I PRd, is there a reason to NOT use beforedraw instead of afterdraw? (always nice to have the option I guess)

**Comment by etimberg** [comment]
@Adondriel i think `beforeDatasetsDraw` is the best place for it. or `afterDatasetsDraw`. Using `beforeDraw` it will get drawn before any axes and grid lines are drawn

**Comment by Adondriel** [comment]
Ah, yes. I can change that for the PR that is currently in place.
