### ISSUE TITLE
Not working on bubble chart

### ISSUE THREAD

**Issue by deviljoshua** [chartjs/Chart.Annotation.js#17]

**Comment by etimberg** [comment]
@deviljoshua can you provide a test case?

**Comment by deviljoshua** [comment]
I was using the wrong scale ID

**Comment by iamandreadompe** [comment]
I reopen this issue, 
with bubble chart you cant set the yAxisID/xAxisID in the dataset,
so this plugin need the scaleID.
The first time i set manually to 'x-axis-0', and it work, but after few days it stopped to work and i saw that the default id of the xAxisID was changed from x-axis-0 to x-axis-1.


In the end we need a way to set (or know) always the name of the axis
