### ISSUE TITLE
How does Annotation Value work?

### ISSUE THREAD

**Issue by deviljoshua** [chartjs/Chart.Annotation.js#18]
I have a bubble chart and I want to create a vertical line on x-axis 1.0, 2.0, 3.0, 4.0

My current configuration is:
```
annotation: {
	annotations: [{
		type: 'line',
		mode: 'vertical',
		scaleID: 'y-axis-0',
		value: '31.5',
		borderColor: '#999999',
		borderWidth: 5
	}]
}
```

![image](https://cloud.githubusercontent.com/assets/20930630/17524294/969c4646-5e90-11e6-9d6f-0365b4864236.png)

 My problem is how does value work because when the window size changes, the vertical line moves as well.

**Comment by jnmills** [comment]
try making your scaleID x-axis instead of y-axis... (see #19)

**Comment by etimberg** [comment]
Closing as resolved.
