### ISSUE TITLE
using sample "line.js" - adding lines - which move about

### ISSUE THREAD

**Issue by jnmills** [chartjs/Chart.Annotation.js#19]
This may be similar to #18, but in trying to understand how things work, I took the sample box.js
which worked consistently, and added a couple of lines - vertical and horizontal.

              annotations: [{
                  type: 'line',
                  mode: 'vertical',
                  scaleID: 'y-axis-1',
                  value: 60,
                  backgroundColor: 'rgba(101, 33, 171, 0.5)',
                  borderColor: 'rgb(101, 33, 171)',
                  borderWidth: 5
              },{
                  type: 'line',
                  mode: 'horizontal',
                  scaleID: 'x-axis-1',
                  value: 30,
                  backgroundColor: 'rgba(101, 33, 171, 0.5)',
                  borderColor: 'rgb(101, 33, 171)',
                  borderWidth: 5
              },{
                  type: 'box',
                  xScaleID: 'x-axis-1',
[and so on]

But when I display it, the lines fall neither on the 60 or the 30 mark.  Even more curious, when you refresh it, the lines are still not on 60 / 30, and they are different to the previous display as well.

is this a fault, or am I driving it incorrectly?

**Comment by jnmills** [comment]
Cancel that - I had swapped the scaleIDs over - the vertical should be x-axis-1 and the horizontal y-axis-1.

Sorry...

**Comment by hultgrrr** [comment]
@jnmills Did you get one or more vertical lines to work in a line graph? If so, mind checking out #20 and see where my code differs from yours since mine aint working? :)
