### ISSUE TITLE
Can't draw vertical lines in line graph

### ISSUE THREAD

**Issue by hultgrrr** [chartjs/Chart.Annotation.js#20]
Hello! Trying to draw multiple vertical lines in a line graph. Horizontal lines works as intended, but as you can see in this fiddle (https://jsfiddle.net/mfjvfz0o/) vertical lines does not work.

Am I doing something wrong or is this a bug?

**Comment by etimberg** [comment]
@hultgrrr these were not supported until v2.2.0 of Chart.js for the category axis. Updated fiddle with this working https://jsfiddle.net/mfjvfz0o/1/

**Comment by hultgrrr** [comment]
Thank you! That did solve my problem!

**Comment by sahilweb6** [comment]
i am facing same roblem using chart.js 2.5 .. whats the soltuion?
