### ISSUE TITLE
Dashed Line Error

### ISSUE THREAD

**Issue by NZguy** [chartjs/Chart.Annotation.js#24]
Using a dashed line as an annotation causes data points and marker lines to also become dashed when the graph updates (when a data point is hovered over or a data set is hidden).

![before](https://cloud.githubusercontent.com/assets/11669953/18234350/cbfea2ae-72b6-11e6-84a7-3fd0f2f7e83d.png)
Before graph update

![after](https://cloud.githubusercontent.com/assets/11669953/18234352/d0f0d084-72b6-11e6-9f75-1a34211093b7.png)
After graph update

I don't know much about js canvas, but it seems that the drawing mode is set to dashed before the annotation is drawn. But the problem occurs because the drawing mode isn't set back to solid before the graph is updated and redrawn.

**Comment by etimberg** [comment]
@NZguy your hunch is correct. https://github.com/chartjs/Chart.Annotation.js/blob/master/src/line.js#L8 needs an update to save and restore the canvas context. I will get on that ASAP
