### ISSUE TITLE
Horizontal line is above tooltips

### ISSUE THREAD

**Issue by lovanwubing** [chartjs/Chart.Annotation.js#28]
![chartiessue](https://cloud.githubusercontent.com/assets/2123441/18981818/1a3d6970-8714-11e6-8886-4a3ad618928f.png)
Please see the picture above. Is there a way to set the line bellow the tooltip ?

**Comment by etimberg** [comment]
At the moment there is no option to do this. You would need to add an option to change where the draw happens.

Currently it happens in https://github.com/chartjs/Chart.Annotation.js/blob/master/src/chart.annotation.js#L67

To put it behind the tooltip it'd need to be in `afterDatasetsDraw`
