### ISSUE TITLE
Horizontal Line not working with my dataset

### ISSUE THREAD

**Issue by shrivardhan92** [chartjs/Chart.Annotation.js#29]
Kindly find the code in the fiddle : [Code](https://jsfiddle.net/srao7/ug0cf0hx/4/)

I have 5 similar charts on the  same page. Annotations don't work on any of them. Unable to find the reason behind this. Please help.

**Comment by etimberg** [comment]
The issue is that the config options were in the wrong spot.

See https://jsfiddle.net/4kt4z7n9/1/

**Comment by shrivardhan92** [comment]
Thank you @etimberg
