### ISSUE TITLE
Line charts seem to not be supported

### ISSUE THREAD

**Issue by iKadmium** [chartjs/Chart.Annotation.js#4]
I could only get line annotations to work with scatter charts.

**Comment by etimberg** [comment]
@iKadmium can you post a fiddle?

**Comment by iKadmium** [comment]
Sure thing :).

https://jsfiddle.net/Kadmium/4xkwnmcw/1/

(this is the bit where I cross my fingers and hope it's not just my own stupid fault)

**Comment by etimberg** [comment]
Updated here https://jsfiddle.net/4p7f2tdx/1/

Default id is 'y-axis-0' and fiddle had scripts in wrong order

**Comment by iKadmium** [comment]
Ahh, I see. Thank you for your help and sorry for wasting your time.

**Comment by etimberg** [comment]
No problem. Glad I could help :smile:
