### ISSUE TITLE
Errors are produced when X values are dates

### ISSUE THREAD

**Issue by iKadmium** [chartjs/Chart.Annotation.js#5]
Moment.js throws an error (Cannot read property 'undefined' of undefined) if the annotation's x-value is a date.

**Comment by etimberg** [comment]
@iKadmium can you post a fiddle? Which version of Chart.js are you using?

**Comment by iKadmium** [comment]
I'm using the 2.1.6 release.
I've honestly never made a fiddle before, but I'll give it a shot. This was created with the latest version of Annotations from github, where the error appears to be a little different.
https://jsfiddle.net/Kadmium/kbp7wkfn/

**Comment by iKadmium** [comment]
(Apologies over the close/reopen. I thought that would close the window, rather than the issue. I'm kinda terrible at this.)

**Comment by etimberg** [comment]
I see the issue. It's a problem inside of Chart.js itself. I will submit a PR there.

**Comment by etimberg** [comment]
Turns out this was fixed in https://github.com/chartjs/Chart.js/pull/2822 and so this will be fixed in the next Chart.js release

**Comment by geraldo** [comment]
Even it is fixed, dates as x-values still don't seem to work: https://jsfiddle.net/geraldo/bvapLgLs/

Any hints?

**Comment by rustam87** [comment]
i have this problem too, i have x in timeformat, and i add value of line  in miliseconds. But it not working
